# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Question Time')),
                ('bot_answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('bot_answer_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Bot Answer Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(auto_now=True, null=True, verbose_name='End Time')),
                ('target_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vicki.UserDetail'),
        ),
        migrations.AddField(
            model_name='predictions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vicki.UserDetail'),
        ),
    ]
