# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vicki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time of Prediction')),
            ],
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Start Time'),
        ),
        migrations.DeleteModel(
            name='Predictions',
        ),
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vicki.UserDetail'),
        ),
    ]
